"""update schema

Revision ID: 0b4fe7004833
Revises: ffcc21ab6b1b
Create Date: 2024-12-14 10:46:08.607623

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b4fe7004833'
down_revision = 'ffcc21ab6b1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cinder_volumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openstack_cinder_volume_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openstack_cinder_volume_id')
    )
    op.create_table('nova_vms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('floating_ip', sa.String(length=100), nullable=True),
    sa.Column('openstack_nova_vm_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openstack_nova_vm_id')
    )
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('storage_in_gb', sa.Float(), nullable=False),
    sa.Column('ram_in_gb', sa.Float(), nullable=False),
    sa.Column('cpu_cores', sa.Integer(), nullable=False),
    sa.Column('has_redis', sa.Boolean(), nullable=False),
    sa.Column('has_mysql', sa.Boolean(), nullable=False),
    sa.Column('monthly_fee_in_usd', sa.Float(), nullable=False),
    sa.Column('image_reference', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_reference')
    )
    op.create_table('websites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('public_port', sa.Integer(), nullable=False),
    sa.Column('nova_vm_port', sa.Integer(), nullable=False),
    sa.Column('nova_vm_id', sa.Integer(), nullable=False),
    sa.Column('cinder_volume_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['cinder_volume_id'], ['cinder_volumes.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['nova_vm_id'], ['nova_vms.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nova_vm_port', 'nova_vm_id', name='unique_nova_vm_port_id'),
    sa.UniqueConstraint('public_port')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)

    op.drop_table('websites')
    op.drop_table('plans')
    op.drop_table('nova_vms')
    op.drop_table('cinder_volumes')
    # ### end Alembic commands ###
