"""empty message

Revision ID: 0b74682782b4
Revises: 5efa7b7d4084
Create Date: 2024-12-25 15:54:43.032273

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b74682782b4'
down_revision = '5efa7b7d4084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_column('docker_compose_plan_url')

    with op.batch_alter_table('websites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', mysql.LONGTEXT(), nullable=True))
        batch_op.add_column(sa.Column('port', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('build_script', mysql.LONGTEXT(), nullable=False))
        batch_op.add_column(sa.Column('start_script', mysql.LONGTEXT(), nullable=False))
        batch_op.add_column(sa.Column('code_zip_url', mysql.LONGTEXT(), nullable=False))
        batch_op.drop_index('public_port')
        batch_op.drop_index('unique_nova_vm_port_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('websites', schema=None) as batch_op:
        batch_op.create_index('unique_nova_vm_port_id', ['nova_vm_port', 'nova_vm_id'], unique=True)
        batch_op.create_index('public_port', ['public_port'], unique=True)
        batch_op.drop_column('code_zip_url')
        batch_op.drop_column('start_script')
        batch_op.drop_column('build_script')
        batch_op.drop_column('port')
        batch_op.drop_column('message')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('docker_compose_plan_url', mysql.LONGTEXT(), nullable=False))

    # ### end Alembic commands ###
