"""empty message

Revision ID: 1b4065d60d8a
Revises: 0b74682782b4
Create Date: 2024-12-25 16:23:52.231266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b4065d60d8a'
down_revision = '0b74682782b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nova_vms', schema=None) as batch_op:
        batch_op.drop_index('openstack_nova_vm_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nova_vms', schema=None) as batch_op:
        batch_op.create_index('openstack_nova_vm_id', ['openstack_nova_vm_id'], unique=True)

    # ### end Alembic commands ###
