version: '3.9'

services:
  app:
    build: .
    container_name: nodejs-app-${WEBSITE_ID}
    ports:
      - "${APP_PORT}:3000" # Map the internal app port
    env_file:
      - .env
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql-container-${WEBSITE_ID}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}  # Use the environment variable
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${_MYSQL_HOST_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
    driver: local

networks:
  app-network:
    driver: bridge
